### PR TITLE
Curl ssl verification fix.

### PR DESCRIPTION
**Pull request by JustinElst**
Todo: add cert with CURLOPT_CAINFO

### CODE REVIEW

**Comment by Pagebakers** [comment]
I'll add the CA bundle to get this fixed properly.

**Comment by Pagebakers** [comment]
Do you guys have experience using this? I tried different CA bundles from our provider, in different formats. But I can't get the cert to be verified.

Bundles can be found here (essentialssl wildcard): 
http://support.openprovider.eu/entries/24120476-List-of-root-and-intermediate-certificates

**Comment by Pagebakers** [comment]
The CA bundle is included in master now, so this work around isn't necessary anymore.

**Comment by JustinElst** [comment]
Great!

**Pull request closed without merging**
